chore: bump version name and code
CUTR-at-USF/MUSER pull request #16
Opened 2020-06-10 20:38 UTC by BumbleFlash

bumped version name to 3.0.1-beta1 and code to 5001

2020-06-10 20:53 UTC, barbeau requested changes
@BumbleFlash Thanks! One requested change in-line on which version number to use.

2020-06-10 20:53 UTC, barbeau commented on buildSrc/src/main/kotlin/Config.kt
> +    const val versionName = "3.0.1-beta1"
Let's use our own versioning scheme for our app - so let's start back over at `1.0.0`.

You can make the change and commit again to the same branch `bump-version2` locally and push to GitHub again, and it will update this pull request with the new commit.

2020-06-10 22:24 UTC, BumbleFlash commented on buildSrc/src/main/kotlin/Config.kt
> +    const val versionName = "3.0.1-beta1"
Sure, will do that. Thank you for letting me know.

2020-06-11 13:59 UTC, barbeau approved these changes

2020-06-11 13:59 UTC, merged

2020-06-11 13:59 UTC, barbeau commented
Thanks @BumbleFlash!