fix: Fix theme
CUTR-at-USF/MUSER pull request #61
Opened 2020-09-15 16:22 UTC by BumbleFlash

This PR is to fix the bug that causes color camouflage when set to the dark theme mentioned in #60. Please uninstall the previous version of the app and reinstall the new version for accurate results. 

Changes:
Set the default theme to be light upon new installation. (I'm guessing since no default theme was set using the `Aesthetic`, the library was sort of misbehaving while changing themes).

"Closes #60"

2020-09-15 20:11 UTC, barbeau requested changes
@BumbleFlash Thanks for working on this!

So it looks like this fixes #60, but there are a few other things that don't look right compared to the `usf` branch.

Here's what this PR looks like:

![image](https://user-images.githubusercontent.com/928045/93259267-94502e00-f76d-11ea-8e22-96703a7a61f4.png)

Problems, from left to right:
* I'd expect the "Library" text in the toolbar to be white in the default light theme
* I'd expect the "Settings" icons on the left to be tinted a light color (not black on black)
* I'd expect the "Themes" and "Palette" text to be a light color (not black on black)

Here's the `usf` branch with the light theme for comparison:

![image](https://user-images.githubusercontent.com/928045/93259515-f7da5b80-f76d-11ea-829a-b9159e5078e0.png)

2020-09-16 14:38 UTC, barbeau commented
@BumbleFlash I just realized that my `usf` branch may have been behind the GitHub `usf` branch when I grabbed the above screenshots, so you may want to test again yourself with the most recent `usf` branch to make sure you see the same thing. All screenshots were on Samsung Galaxy S8+ w/ Android 9.

2020-09-16 16:04 UTC, BumbleFlash commented
@barbeau  Thanks for testing it out. Since we were ignoring `Aesthetic` altogether, I'm guessing we didn't have a default color set for the Views when the Light theme was being used. I set the default colors during the views that were initially in black. Also, for some reason, I was not quite able to reproduce the 2 & 3. Let me know if the problem still persists on your end,

2020-09-16 16:29 UTC, barbeau commented
@BumbleFlash Thanks, I'll take a look. Is the default theme supposed to still be light now? Looks like it's dark now from a quick test.

2020-09-16 16:58 UTC, BumbleFlash commented
@barbeau I removed the block of code that initially set the default theme to Light. When the user installs the app for the first time, the MainActivity in which the permission dialog pops up is always set to dark and the transition to Light isn't smooth after the user gives storage permissions. I'm guessing the theme would be dark on start-up.

2020-09-16 19:24 UTC, barbeau commented
Ok - is there a way to keep the initial default theme as Light? I think more users may prefer that, and I can confirm that currently this PR does have a default of dark.

Below are the current themes. The previous issues I mentioned above do seem to be gone, which is good. One remaining issue I see is that the ribbon for "Suggested, Artists, etc." has black text in the light theme when I believe it should still have white text (i.e., this shouldn't change between themes).

![image](https://user-images.githubusercontent.com/928045/93382737-8ca58d80-f830-11ea-97fb-b95d165a7646.png)

2020-09-17 14:56 UTC, BumbleFlash commented
@barbeau Update: I have also noticed the Hamburger icon and search icon on the top-left corner changes to black for selective songs. I have set the default color to be white to the search icon and currently looking for ways to make the hamburger icon white. 

As far as ViewPager `tablayout` is concerned, I tried a few things that supposedly worked for other developers but unfortunately I can't say the same to us. What I noticed is the text color in the `tablayout` is initially white, but it changes to black once a song is loaded. `Aesthetic` doesn't explicitly provide a way to ignore the "text" on the `tablayout`. 

Here are the few things that I tried yesterday evening:-

1) Tried to change the color by setting `android:tabTextColor` directly to the `tablayout` in the XML. 
2) Tried setting the colors programmatically at the end of `onCreate` function.   `slidingTabLayout.setTabTextColor()`. 
3) Created a custom `TextView` and attached it to the `tablayout` as shown [here ](https://stackoverflow.com/questions/47616112/how-to-change-text-color-of-tab-layout). By doing this, the font of the text changes but not its color. 
4) Lastly, I set the colors to `styles.xml` and added it to the layout as shown [here](https://stackoverflow.com/a/31153743). 

Currently, I'm looking for any possible `Aesthetic ` involvement in or near the `LibraryController` that's potentially causing this issue.

2020-09-18 17:36 UTC, BumbleFlash commented
@barbeau I have created another PR (#63) per discussion today, also pushed the changes that used the `handler` to sort of delay the setting of colors to this current PR. We could do an A/B testing if you'd like to compare and look for any difference in performance. From a quick view, I found the new PR seems to be more smooth and neat compared to the current one. Let me know your thoughts.

2020-09-22 14:20 UTC, barbeau commented
Closed in favor https://github.com/CUTR-at-USF/MUSER/pull/63, which has the same end result but with less manual editing of colors.

2020-09-22 14:20 UTC, closed without merging